version: "2"
services:
  tipask:
    image: neuinet/tipask-docker
    links:
      - mysql
    environment:
      - VIRTUAL_HOST=neui.net
      - DB_HOST=mysql
      - DB_DATABASE=tipaskx
      - DB_USER=tipaskdb
      - DB_PASSWORD=password1

  mysql:
    image: mysql:5.6
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=tipaskx
      - MYSQL_USER=tipaskdb
      - MYSQL_PASSWORD=password1
      - MYSQL_ROOT_PASSWORD=password1

volumes:
  mysql:

networks:
  default:
    external:
      name: nginx-proxy

