version: "2"
services:
  tipask:
    image: xujingguo58/tipask-docker
    ports:
      - "80:80"
    links:
      - mysql

  mysql:
    image: mysql:5.6
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=tipaskx
      - MYSQL_USER=tipaskdb
      - MYSQL_PASSWORD=password1
      - MYSQL_ROOT_PASSWORD=password1

volumes:
  mysql:
